services:
  # mongo_db:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_db_data:/data/db
  #     - ./db/books.json:/docker-entrypoint-initdb.d/books.json
  #   environment:
  #     # MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
  #     # MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  #     # MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
  #     MONGO_INITDB_DATABASE: bookstore
  #   restart: always
  #   env_file:
  #     - ../.env

  mountebank:
    build:
      context: ./mountebank
      dockerfile: ./Dockerfile
    container_name: mountebank
    volumes:
      - ./mountebank:/imposters
    command: [ "--configfile", "/imposters/payment-mock.json" ]
    ports:
      - "2525:2525"
      - "8081:8081"

volumes:
  mountebank_data:
    # mongo_db_data:

